sudo: false
language: node_js
node_js:
- iojs
- '0.12'
before_script:
- npm install
script: npm run build
notifications:
  slack:
    secure: 2LhA0LdafA20Sy2x0yv4f2UInAxqPgHbAKF3qozzv7+8RprVhrwyvHCgACwlYcnWSeCYrsiC6jsZfpevkXdrrfdauSLAF5oQj8+UgcLsh4eN+YhRRpA/RVdtLFJS3ivn2FQsm3ixdhs+ytOplpzd+D/LeB3Hl1JT06zJ6xIYNb8kF7nw2DgHEQH1+uN3wW9qGSEp57Fi8pF8AnRbNaH5bX47lIjuVXVCHa+Q14ucShe6jvZI1JDDpv7FAdea6AeGmpQNWc7b+uF6T1eBZ1POmRBGoQvRKMbke93zURHbpw8U8xQ78oGwNMNVsY2WeBD9TKz48BXiBZMKCxt0MWM3DlZnJcA5kjU4k45GVYc9yz5AXbn8Az+3aB6chdOgUgxUvs/dP3vGJaQOvqP7xOg4MinMB/PMYrvy8t2v8FyeQW1SGD+6JkHznU8R7MbNZnyYIUKLk5y12xiFuOuYJPhizWHtcY+BuPABklobt/FoAfHx3jXPwnySYjk9tR00xllFKb7kUvoUUDNqDzR/j4RfVhgFoz95DyYMMocT1USeo2Ch731TtgZFuNHcW0QQKnq9OvG4knoZOl+84dhVVBDP2LHjF32stPaS2k1snjqR8De03PcMgGp9S5WILGZFZgq3W4iDQhiv3UTV01JUOvr+lD79i5tsU9gKvrpm6Id+yRo=
